FROM node:20-alpine as build

WORKDIR /app/

COPY package*.json ./

#RUN npm install
RUN npm ci

COPY . ./

EXPOSE 3001

#Avant pour le DEV : CMD ["npm", "run", "dev"]
RUN npm run build


# ===== PROD =====
FROM nginx:alpine

# Supprime la conf par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Ajoute ta conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copie le build Vite
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
